### ISSUE TITLE
Is it possible to specify input data....?

### ISSUE THREAD

**Issue by pconesa** [cdienem/AutoSparc#1]
Nice stuff @cdienem ... I might be missing something, but is there a way to specify with dataset to use....let's say we have some particles (.stk) and some metadata (relion, eman, other).

**Comment by cdienem** [comment]
Hi. You have to create a data set in CryoSPARC first (e.g. import starfile from Relion) and then create a template experiment that uses this data. The script will just read the template experiment (including the info which data set to use) and submit a new experiment based on that template.

The good thing is that if your starfile grows larger during your data collection, cryoSPARC will re-read the specified starfile each time and therefore also load the newly picked particles.

I am sorry that the implementation is still rather crude. In principle one could also create a data set in the data base (datasets table), launch a data visualization job (via the jobs table) and then use this data set for other experiments (via the experiments and jobs table). I am still waiting for cryoSPARCv2 before I think of making an effort to design a more thorough cmd interface for cryoSPARC.

**Comment by alipunjani** [comment]
Nice @cdienem!
Just to chime in, v2 will have full support for scripting and automation like this. In v2 anything you can do via the UI you can do via the CLI, and you can also query job status, wait for jobs to complete, connect inputs and outputs, etc.

**Comment by pconesa** [comment]
so, @alipunjani does this means that integration will be easier? Thanks @cdienem also for sharing your work.

**Comment by pconesa** [comment]
@alipunjani, what's the status of this? Did it happened?
